name: 'Environment Variables from Dotenv'
author: "c-py"
description: 'Export environment variables from a "dotenv" file into GitHub Actions via set-env workflow commands'
branding:
  icon: settings
  color: orange
inputs:
  env-file:
    description: 'Path to the .env file (Default: .env)'
    required: true
    default: '.env'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.env-file }}
